### ISSUE TITLE
Print Label button not clickable

### ISSUE THREAD

**Issue by jeeyer** [jackgregory/woocommerce-dymo-barcodes#1]
Hey!

First of all; thank you so much for creating this plugin. It's exactly what I'm looking for!
I first bought a Zebra printer but it's a nightmare, bought a Demo because of this plugin.

I was trying to print directly from my Safari browser but I can't seem to enable the print label button. It seems un-clickable.

I'm trying this on a Mac OS El Captain  / 10.11.2
Safari: Version 9.0.2 (11601.3.9)

See screen: https://monosnap.com/file/x65grcCrD8IMVO7n3GEKi1MHbmFrhM

Thanks for all the help!

**Comment by jackgregory** [comment]
@jeeyer 

Can you add a screenshot of your error console?

[https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Safari](https://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors#Safari)

**Comment by jeeyer** [comment]
@jackgregory 

Hey Jack thanks for helping out. 

Not sure if this is what you are looking for: https://monosnap.com/file/3deQ2G4uGfdeB9glZ7eDPYHbdluWw5

**Comment by jackgregory** [comment]
@jeeyer 

Thanks. Think Ive found the issue fixed in 69c7cfb. Can you try replacing the plugin with the latest master branch and let me know if it works for you?

**Comment by jeeyer** [comment]
@jackgregory

Hey thanks for this. I've updated the plugin by downloading the download button at the "code" tap here on github. I've deleted the latest version, re-installed and activated and cleared cache. I've re-opened safari but problem remains I'm afraid.

Can I provide you with additional information from my end?
Thanks,
Joost

**Comment by jackgregory** [comment]
@jeeyer have you cleared your browser cache and refreshed the admin?

**Comment by jeeyer** [comment]
@jackgregory no I didn't clear browser cache. Did it now, and rebooted Safari (browsing without cache now) and I'm afraid it's not clickable.

See a screencast here: http://take.ms/2n38o

Thanks again!

**Comment by jackgregory** [comment]
@jeeyer Can you give me access to your install so I can take a look? Email to jackjlgregory@gmail.com
